# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulateTrials <- function(allpaths, turnTimes, alpha, model, turnMethod) {
    .Call(`_baseModels_simulateTrials`, allpaths, turnTimes, alpha, model, turnMethod)
}

getPathLikelihood <- function(allpaths, alpha, H, sim, model, policyMethod, epsilon = 0, endTrial = 0L) {
    .Call(`_baseModels_getPathLikelihood`, allpaths, alpha, H, sim, model, policyMethod, epsilon, endTrial)
}

getProbMatrix <- function(allpaths, alpha, H, sim, model, policyMethod, epsilon = 0, endTrial = 0L) {
    .Call(`_baseModels_getProbMatrix`, allpaths, alpha, H, sim, model, policyMethod, epsilon, endTrial)
}

getEpisodes <- function(allpaths) {
    .Call(`_baseModels_getEpisodes`, allpaths)
}

rcpparma_hello_world <- function() {
    .Call(`_baseModels_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_baseModels_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_baseModels_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_baseModels_rcpparma_bothproducts`, x)
}

getPathTimes <- function(allpaths, enreg_pos) {
    .Call(`_baseModels_getPathTimes`, allpaths, enreg_pos)
}

empiricalProbMat <- function(allpaths, window) {
    .Call(`_baseModels_empiricalProbMat`, allpaths, window)
}

empiricalProbMat2 <- function(allpaths, window) {
    .Call(`_baseModels_empiricalProbMat2`, allpaths, window)
}

mseEmpirical <- function(allpaths, probMatrix_m1, movAvg, sim) {
    .Call(`_baseModels_mseEmpirical`, allpaths, probMatrix_m1, movAvg, sim)
}

pathProbability <- function(allpaths, probMatrix_m1, sim) {
    .Call(`_baseModels_pathProbability`, allpaths, probMatrix_m1, sim)
}

getBoxTimes <- function(enregPosTimes, rleLengths) {
    .Call(`_baseModels_getBoxTimes`, enregPosTimes, rleLengths)
}

getTurnsFromPaths <- function(path, state) {
    .Call(`_baseModels_getTurnsFromPaths`, path, state)
}

getTurnString <- function(turnNb) {
    .Call(`_baseModels_getTurnString`, turnNb)
}

getTurnIdx <- function(turn, state) {
    .Call(`_baseModels_getTurnIdx`, turn, state)
}

getTurnTimes <- function(allpaths, boxTimes, sim) {
    .Call(`_baseModels_getTurnTimes`, allpaths, boxTimes, sim)
}

getComputationalActivity <- function(allpaths, probabilityMatrix) {
    .Call(`_baseModels_getComputationalActivity`, allpaths, probabilityMatrix)
}

getPathFromTurns <- function(turns, state) {
    .Call(`_baseModels_getPathFromTurns`, turns, state)
}

