# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulateTrials <- function(allpaths, H, alpha, total_trials, init_state, model) {
    .Call(`_baseModels_simulateTrials`, allpaths, H, alpha, total_trials, init_state, model)
}

getPathLikelihood <- function(allpaths, alpha, H, sim, model) {
    .Call(`_baseModels_getPathLikelihood`, allpaths, alpha, H, sim, model)
}

getProbMatrix <- function(allpaths, alpha, H, sim, model) {
    .Call(`_baseModels_getProbMatrix`, allpaths, alpha, H, sim, model)
}

rcpparma_hello_world <- function() {
    .Call(`_baseModels_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_baseModels_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_baseModels_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_baseModels_rcpparma_bothproducts`, x)
}

getTrialTimes <- function(allpaths, enreg_pos) {
    .Call(`_baseModels_getTrialTimes`, allpaths, enreg_pos)
}

empiricalProbMat <- function(allpaths, window) {
    .Call(`_baseModels_empiricalProbMat`, allpaths, window)
}

mseEmpirical <- function(allpaths, probMatrix_m1, movAvg, sim) {
    .Call(`_baseModels_mseEmpirical`, allpaths, probMatrix_m1, movAvg, sim)
}

pathProbability <- function(allpaths, probMatrix_m1, sim) {
    .Call(`_baseModels_pathProbability`, allpaths, probMatrix_m1, sim)
}

