# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_Sarsa_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_Sarsa_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_Sarsa_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_Sarsa_rcpparma_bothproducts`, x)
}

simulateSarsa <- function(allpaths, turnTimes, alpha, gamma, lambda, rewardVal, turnMethod) {
    .Call(`_Sarsa_simulateSarsa`, allpaths, turnTimes, alpha, gamma, lambda, rewardVal, turnMethod)
}

getPathLikelihood <- function(allpaths, alpha, gamma, lambda, rewardVal, Q, sim, policyMethod, epsilon = 0) {
    .Call(`_Sarsa_getPathLikelihood`, allpaths, alpha, gamma, lambda, rewardVal, Q, sim, policyMethod, epsilon)
}

getProbMatrix <- function(allpaths, alpha, gamma, lambda, rewardVal, Q, sim, policyMethod, epsilon = 0) {
    .Call(`_Sarsa_getProbMatrix`, allpaths, alpha, gamma, lambda, rewardVal, Q, sim, policyMethod, epsilon)
}

getTurnString <- function(turnNb) {
    .Call(`_Sarsa_getTurnString`, turnNb)
}

getTurnIdx <- function(turn, state) {
    .Call(`_Sarsa_getTurnIdx`, turn, state)
}

getTurnsFromPaths <- function(path, state) {
    .Call(`_Sarsa_getTurnsFromPaths`, path, state)
}

getTurnTimes <- function(allpaths, boxTimes, sim) {
    .Call(`_Sarsa_getTurnTimes`, allpaths, boxTimes, sim)
}

