# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_Sarsa_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_Sarsa_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_Sarsa_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_Sarsa_rcpparma_bothproducts`, x)
}

simulateSarsa <- function(allpaths, Q, alpha, gamma, lambda, model, policyMethod, epsilon = 0) {
    .Call(`_Sarsa_simulateSarsa`, allpaths, Q, alpha, gamma, lambda, model, policyMethod, epsilon)
}

getPathLikelihood <- function(allpaths, alpha, gamma, lambda, Q, sim, policyMethod, epsilon = 0) {
    .Call(`_Sarsa_getPathLikelihood`, allpaths, alpha, gamma, lambda, Q, sim, policyMethod, epsilon)
}

getProbMatrix <- function(allpaths, alpha, gamma, lambda, Q, sim, policyMethod, epsilon = 0) {
    .Call(`_Sarsa_getProbMatrix`, allpaths, alpha, gamma, lambda, Q, sim, policyMethod, epsilon)
}

