# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulateTurnsModels <- function(allpaths, turnTimes, alpha, gamma1, turnMethod) {
    .Call(`_Aca2Turns_simulateTurnsModels`, allpaths, turnTimes, alpha, gamma1, turnMethod)
}

getTurnsLikelihood <- function(allpaths, turnTimes, turnMethod, alpha, gamma1, rewardVal, sim) {
    .Call(`_Aca2Turns_getTurnsLikelihood`, allpaths, turnTimes, turnMethod, alpha, gamma1, rewardVal, sim)
}

getProbMatrix <- function(allpaths, turnTimes, turnMethod, alpha, gamma1, rewardVal, sim) {
    .Call(`_Aca2Turns_getProbMatrix`, allpaths, turnTimes, turnMethod, alpha, gamma1, rewardVal, sim)
}

rcpparma_hello_world <- function() {
    .Call(`_Aca2Turns_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_Aca2Turns_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_Aca2Turns_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_Aca2Turns_rcpparma_bothproducts`, x)
}

getTrialTimes <- function(allpaths, enreg_pos) {
    .Call(`_Aca2Turns_getTrialTimes`, allpaths, enreg_pos)
}

empiricalProbMat <- function(allpaths, window) {
    .Call(`_Aca2Turns_empiricalProbMat`, allpaths, window)
}

mseEmpirical <- function(allpaths, probMatrix_m1, movAvg, sim) {
    .Call(`_Aca2Turns_mseEmpirical`, allpaths, probMatrix_m1, movAvg, sim)
}

pathProbability <- function(allpaths, probMatrix_m1, sim) {
    .Call(`_Aca2Turns_pathProbability`, allpaths, probMatrix_m1, sim)
}

getBoxTimes <- function(enregPosTimes, rleLengths) {
    .Call(`_Aca2Turns_getBoxTimes`, enregPosTimes, rleLengths)
}

getTurnsFromPaths <- function(path, state) {
    .Call(`_Aca2Turns_getTurnsFromPaths`, path, state)
}

getTurnString <- function(turnNb) {
    .Call(`_Aca2Turns_getTurnString`, turnNb)
}

getTurnIdx <- function(turn, state) {
    .Call(`_Aca2Turns_getTurnIdx`, turn, state)
}

getTurnTimes <- function(allpaths, boxTimes) {
    .Call(`_Aca2Turns_getTurnTimes`, allpaths, boxTimes)
}

getPathFromTurns <- function(turns, state) {
    .Call(`_Aca2Turns_getPathFromTurns`, turns, state)
}

