# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulateTrials <- function(allpaths, turnTimes, alpha, gamma1, gamma2, turnMethod) {
    .Call(`_Aca3_simulateTrials`, allpaths, turnTimes, alpha, gamma1, gamma2, turnMethod)
}

getPathLikelihood <- function(allpaths, alpha, gamma1, gamma2, H, sim, model, policyMethod, epsilon = 0, endTrial = 0L) {
    .Call(`_Aca3_getPathLikelihood`, allpaths, alpha, gamma1, gamma2, H, sim, model, policyMethod, epsilon, endTrial)
}

getProbMatrix <- function(allpaths, alpha, gamma1, gamma2, H, sim, model, policyMethod, epsilon = 0) {
    .Call(`_Aca3_getProbMatrix`, allpaths, alpha, gamma1, gamma2, H, sim, model, policyMethod, epsilon)
}

rcpparma_hello_world <- function() {
    .Call(`_Aca3_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_Aca3_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_Aca3_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_Aca3_rcpparma_bothproducts`, x)
}

getTurnsFromPaths <- function(path, state) {
    .Call(`_Aca3_getTurnsFromPaths`, path, state)
}

getTurnString <- function(turnNb) {
    .Call(`_Aca3_getTurnString`, turnNb)
}

getTurnIdx <- function(turn, state) {
    .Call(`_Aca3_getTurnIdx`, turn, state)
}

getTurnTimes <- function(allpaths, boxTimes, sim) {
    .Call(`_Aca3_getTurnTimes`, allpaths, boxTimes, sim)
}

