# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getTurnsLikelihood <- function(allpaths, turnTimes, turnMethod, alpha, sim, model) {
    .Call(`_TurnsModels_getTurnsLikelihood`, allpaths, turnTimes, turnMethod, alpha, sim, model)
}

getProbMatrix <- function(allpaths, turnTimes, turnMethod, alpha, sim, model) {
    .Call(`_TurnsModels_getProbMatrix`, allpaths, turnTimes, turnMethod, alpha, sim, model)
}

rcpparma_hello_world <- function() {
    .Call(`_TurnsModels_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_TurnsModels_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_TurnsModels_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_TurnsModels_rcpparma_bothproducts`, x)
}

getTrialTimes <- function(allpaths, enreg_pos) {
    .Call(`_TurnsModels_getTrialTimes`, allpaths, enreg_pos)
}

empiricalProbMat <- function(allpaths, window) {
    .Call(`_TurnsModels_empiricalProbMat`, allpaths, window)
}

mseEmpirical <- function(allpaths, probMatrix_m1, movAvg, sim) {
    .Call(`_TurnsModels_mseEmpirical`, allpaths, probMatrix_m1, movAvg, sim)
}

pathProbability <- function(allpaths, probMatrix_m1, sim) {
    .Call(`_TurnsModels_pathProbability`, allpaths, probMatrix_m1, sim)
}

getBoxTimes <- function(enregPosTimes, rleLengths) {
    .Call(`_TurnsModels_getBoxTimes`, enregPosTimes, rleLengths)
}

getTurnsFromPaths <- function(path, state) {
    .Call(`_TurnsModels_getTurnsFromPaths`, path, state)
}

getTurnString <- function(turnNb) {
    .Call(`_TurnsModels_getTurnString`, turnNb)
}

getTurnIdx <- function(turn, state) {
    .Call(`_TurnsModels_getTurnIdx`, turn, state)
}

getTurnTimes <- function(allpaths, boxTimes) {
    .Call(`_TurnsModels_getTurnTimes`, allpaths, boxTimes)
}

