# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_SarsaTurns_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_SarsaTurns_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_SarsaTurns_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_SarsaTurns_rcpparma_bothproducts`, x)
}

simulateSarsa <- function(allpaths, turnTimes, alpha, gamma, lambda, rewardVal, turnMethod) {
    .Call(`_SarsaTurns_simulateSarsa`, allpaths, turnTimes, alpha, gamma, lambda, rewardVal, turnMethod)
}

getTurnsLikelihood <- function(allpaths, alpha, gamma, lambda, rewardVal, sim) {
    .Call(`_SarsaTurns_getTurnsLikelihood`, allpaths, alpha, gamma, lambda, rewardVal, sim)
}

getProbMatrix <- function(allpaths, alpha, gamma, lambda, rewardVal, sim) {
    .Call(`_SarsaTurns_getProbMatrix`, allpaths, alpha, gamma, lambda, rewardVal, sim)
}

getTrialTimes <- function(allpaths, enreg_pos) {
    .Call(`_SarsaTurns_getTrialTimes`, allpaths, enreg_pos)
}

empiricalProbMat <- function(allpaths, window) {
    .Call(`_SarsaTurns_empiricalProbMat`, allpaths, window)
}

mseEmpirical <- function(allpaths, probMatrix_m1, movAvg, sim) {
    .Call(`_SarsaTurns_mseEmpirical`, allpaths, probMatrix_m1, movAvg, sim)
}

pathProbability <- function(allpaths, probMatrix_m1, sim) {
    .Call(`_SarsaTurns_pathProbability`, allpaths, probMatrix_m1, sim)
}

getBoxTimes <- function(enregPosTimes, rleLengths) {
    .Call(`_SarsaTurns_getBoxTimes`, enregPosTimes, rleLengths)
}

getTurnsFromPaths <- function(path, state) {
    .Call(`_SarsaTurns_getTurnsFromPaths`, path, state)
}

getPathFromTurns <- function(turns, state) {
    .Call(`_SarsaTurns_getPathFromTurns`, turns, state)
}

getTurnString <- function(turnNb) {
    .Call(`_SarsaTurns_getTurnString`, turnNb)
}

getTurnIdx <- function(turn, state) {
    .Call(`_SarsaTurns_getTurnIdx`, turn, state)
}

