# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulateTrials <- function(allpaths, turnTimes, alpha, gamma1, turnMethod) {
    .Call(`_Aca2_simulateTrials`, allpaths, turnTimes, alpha, gamma1, turnMethod)
}

getPathLikelihood <- function(allpaths, alpha, gamma1, H, sim, model, policyMethod, epsilon = 0, endTrial = 0L) {
    .Call(`_Aca2_getPathLikelihood`, allpaths, alpha, gamma1, H, sim, model, policyMethod, epsilon, endTrial)
}

getProbMatrix <- function(allpaths, alpha, gamma1, H, sim, model, policyMethod, epsilon = 0) {
    .Call(`_Aca2_getProbMatrix`, allpaths, alpha, gamma1, H, sim, model, policyMethod, epsilon)
}

rcpparma_hello_world <- function() {
    .Call(`_Aca2_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_Aca2_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_Aca2_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_Aca2_rcpparma_bothproducts`, x)
}

getTurnsFromPaths <- function(path, state) {
    .Call(`_Aca2_getTurnsFromPaths`, path, state)
}

getTurnString <- function(turnNb) {
    .Call(`_Aca2_getTurnString`, turnNb)
}

getTurnIdx <- function(turn, state) {
    .Call(`_Aca2_getTurnIdx`, turn, state)
}

getTurnTimes <- function(allpaths, boxTimes, sim) {
    .Call(`_Aca2_getTurnTimes`, allpaths, boxTimes, sim)
}

