# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DEoptim_impl <- function(minbound, maxbound, fnS, control, rhoS) {
    .Call(`_RcppDE1_DEoptim_impl`, minbound, maxbound, fnS, control, rhoS)
}

putFunPtrInXPtr <- function(funname) {
    .Call(`_RcppDE1_putFunPtrInXPtr`, funname)
}

loopDEoptim <- function(minbound, maxbound, fnS, control, rhoS1, rhoS2, rhoS3) {
    .Call(`_RcppDE1_loopDEoptim`, minbound, maxbound, fnS, control, rhoS1, rhoS2, rhoS3)
}

