# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulateTrials <- function(allpaths, H, alpha, total_trials, init_state, model) {
    .Call(`_turnModels_simulateTrials`, allpaths, H, alpha, total_trials, init_state, model)
}

getTurnsLikelihood <- function(allpaths, alpha, H, sim, model) {
    .Call(`_turnModels_getTurnsLikelihood`, allpaths, alpha, H, sim, model)
}

getProbMatrix <- function(allpaths, alpha, H, sim, model) {
    .Call(`_turnModels_getProbMatrix`, allpaths, alpha, H, sim, model)
}

rcpparma_hello_world <- function() {
    .Call(`_turnModels_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_turnModels_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_turnModels_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_turnModels_rcpparma_bothproducts`, x)
}

getTrialTimes <- function(allpaths, enreg_pos) {
    .Call(`_turnModels_getTrialTimes`, allpaths, enreg_pos)
}

empiricalProbMat <- function(allpaths, window) {
    .Call(`_turnModels_empiricalProbMat`, allpaths, window)
}

mseEmpirical <- function(allpaths, probMatrix_m1, movAvg, sim) {
    .Call(`_turnModels_mseEmpirical`, allpaths, probMatrix_m1, movAvg, sim)
}

pathProbability <- function(allpaths, probMatrix_m1, sim) {
    .Call(`_turnModels_pathProbability`, allpaths, probMatrix_m1, sim)
}

getBoxTimes <- function(enregPosTimes, rleLengths) {
    .Call(`_turnModels_getBoxTimes`, enregPosTimes, rleLengths)
}

getTurnsFromPaths <- function(path, state) {
    .Call(`_turnModels_getTurnsFromPaths`, path, state)
}

getTurnString <- function(turnNb) {
    .Call(`_turnModels_getTurnString`, turnNb)
}

getTurnIdx <- function(turn) {
    .Call(`_turnModels_getTurnIdx`, turn)
}

getTurnTimes <- function(allpaths, boxTimes) {
    .Call(`_turnModels_getTurnTimes`, allpaths, boxTimes)
}

