# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulateTrials <- function(allpaths, H, alpha, total_trials, init_state, model) {
    .Call(`_baseModel_simulateTrials`, allpaths, H, alpha, total_trials, init_state, model)
}

getPathLikelihood <- function(allpaths, alpha, H, sim, model) {
    .Call(`_baseModel_getPathLikelihood`, allpaths, alpha, H, sim, model)
}

getProbMatrix <- function(allpaths, alpha, H, sim, model) {
    .Call(`_baseModel_getProbMatrix`, allpaths, alpha, H, sim, model)
}

rcpparma_hello_world <- function() {
    .Call(`_baseModel_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_baseModel_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_baseModel_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_baseModel_rcpparma_bothproducts`, x)
}

