# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulateTurnsModels <- function(allpaths, turnTimes, alpha, gamma1, gamma2, turnStages) {
    .Call(`_TurnsNew_simulateTurnsModels`, allpaths, turnTimes, alpha, gamma1, gamma2, turnStages)
}

getTurnsLikelihood <- function(allpaths, turnTimes, alpha, gamma1, gamma2, rewardVal, sim) {
    .Call(`_TurnsNew_getTurnsLikelihood`, allpaths, turnTimes, alpha, gamma1, gamma2, rewardVal, sim)
}

getProbMatrix <- function(allpaths, turnTimes, alpha, gamma1, gamma2, rewardVal, sim) {
    .Call(`_TurnsNew_getProbMatrix`, allpaths, turnTimes, alpha, gamma1, gamma2, rewardVal, sim)
}

rcpparma_hello_world <- function() {
    .Call(`_TurnsNew_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_TurnsNew_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_TurnsNew_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_TurnsNew_rcpparma_bothproducts`, x)
}

getTrialTimes <- function(allpaths, enreg_pos) {
    .Call(`_TurnsNew_getTrialTimes`, allpaths, enreg_pos)
}

empiricalProbMat <- function(allpaths, window) {
    .Call(`_TurnsNew_empiricalProbMat`, allpaths, window)
}

mseEmpirical <- function(allpaths, probMatrix_m1, movAvg, sim) {
    .Call(`_TurnsNew_mseEmpirical`, allpaths, probMatrix_m1, movAvg, sim)
}

pathProbability <- function(allpaths, probMatrix_m1, sim) {
    .Call(`_TurnsNew_pathProbability`, allpaths, probMatrix_m1, sim)
}

getBoxTimes <- function(enregPosTimes, rleLengths) {
    .Call(`_TurnsNew_getBoxTimes`, enregPosTimes, rleLengths)
}

getTurnsFromPaths <- function(path, state) {
    .Call(`_TurnsNew_getTurnsFromPaths`, path, state)
}

getTurnString <- function(turnNb) {
    .Call(`_TurnsNew_getTurnString`, turnNb)
}

getTurnIdx <- function(turn, state) {
    .Call(`_TurnsNew_getTurnIdx`, turn, state)
}

getPathFromTurns <- function(turns, state) {
    .Call(`_TurnsNew_getPathFromTurns`, turns, state)
}

quartiles <- function(samples) {
    .Call(`_TurnsNew_quartiles`, samples)
}

simulateTurnDuration <- function(turnTimes, allpaths, turnId, turnNb, turnStages) {
    .Call(`_TurnsNew_simulateTurnDuration`, turnTimes, allpaths, turnId, turnNb, turnStages)
}

